config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'
  devise_for :users
  resources :users
  resources :recipes do
    get 'search_api', on: :collection
    get 'search', on: :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    registration_params = [:name, :email, :password, :password_confirmation, :commit]

    if params[:action] == 'update'
      registration_params << :current_password
      devise_parameter_sanitizer.permit(:account_update, keys: registration_params)
    elsif params[:action] == 'create'
      devise_parameter_sanitizer.permit(:sign_up, keys: registration_params)
    end
  end
end

app/controllers/recipes_controller.rb
# frozen_string_literal: true

class RecipesController < ApplicationController
  before_action :authenticate_user!, except: %i[show index search search_api search_tags_api]

  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    tags = @recipe.tags.split(',')
    tags.map!(&:strip)
    tags.uniq!
    @recipe.tags = tags.join(',')

    if @recipe.save
      redirect_to @recipe
    else
      render 'new'
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])

    if @recipe.user_id == current_user.id
      if @recipe.update(recipe_params)
        redirect_to @recipe
      else
        render 'edit'
      end
    end
  end

  def index
    redirect_to action: 'search'
  end

  def search
    @recipes = []
    @recipes = search_api if params.include? :term
    @recipes = search_tags_api if params.include? :tag
  end

  def search_api
    limit = params[:limit] || 10
    page = params[:page] || 1
    offset = ((page - 1) * limit) || 0
    term = params[:term] || nil
    if term
      Recipe.where('lower(title) LIKE ? '\
                   'OR lower(content) LIKE ? '\
                   'OR lower(ingredients) LIKE ? '\
                   'OR lower(tags) LIKE ?',
                   "%#{term.downcase}%",
                   "%#{term.downcase}%",
                   "%#{term.downcase}%",
                   "%#{term.downcase}%")
            .limit(limit)
            .offset(offset)
    end
  end

  def search_tags_api
    limit = params[:limit] || 10
    page = params[:page] || 1
    offset = ((page - 1) * limit) || 0
    term = params[:tag] || nil
    term = URI.decode term
    if term
      Recipe.where('lower(tags) LIKE ? ', "%#{term.downcase}%")
            .limit(limit)
            .offset(offset)
    end
  end

  def generate_tag_css(tag)
    bg_colors = generate_tag_color tag
    background_color = format('#%02X%02X%02X', bg_colors[0], bg_colors[1], bg_colors[2])

    fg_colors = generate_tag_text_color bg_colors
    color = format('#%02X%02X%02X', fg_colors[0], fg_colors[1], fg_colors[2])

    "color: #{color};\nbackground-color: #{background_color};"
  end
  helper_method :generate_tag_css

  private

  def recipe_params
    created_at = if !@recipe.nil?
                   @recipe.created_at
                 else
                   Time.now
                 end

    params.require(:recipe)
          .merge!(user_id: current_user.id,
                  created_at: created_at,
                  updated_at: Time.now)
          .permit(:title,
                  :content,
                  :ingredients,
                  :notes,
                  :updated_at,
                  :created_at,
                  :user_id,
                  :tags,
                  :source)
  end

  def get_specific_tag_color(tag)
    case tag.downcase
    when 'christmas'
      [154, 205, 50]
    when 'easy'
      [50, 205, 50]
    when 'medium'
      [255, 165, 0]
    when 'hard'
      [255, 0, 0]
    end
  end

  def color_high(random)
    (random.rand * 64) + 192
  end

  def color_middle(random)
    (random.rand * 64) + 128
  end

  def color_low(random)
    random.rand * 64
  end

  def color_high_low(random)
    high_bit = (random.rand + 0.5).to_i
    random.rand * 64 + (128 * high_bit)
  end

  def color_random(random)
    random.rand * 256
  end

  def generate_tag_color(tag)
    # Short-circuit custom tag names
    specific = get_specific_tag_color tag
    return specific unless specific.nil?

    # Randomly generate a color using a custom high-low selection strategy
    seed = tag.bytes.map(&:to_i).reduce(0, :+)
    r = Random.new(seed)
    a = (r.rand * 64).to_i * 4
    b = (r.rand * 64).to_i * 4

    # TODO: DRY
    if a >= 192 && b >= 192
      # high high
      c = color_low(r)
    elsif (a >= 192 && b >= 64 && b < 192) || (a >= 64 && a < 192 && b >= 192)
      # high medium
      c = color_random(r)
    elsif (a >= 192 && b < 64) || (a < 64 && b >= 192)
      # high low
      c = color_high_low(r)
    elsif a >= 64 && a < 192 && b >= 64 && b < 192
      # middle middle
      c = color_high_low(r)
    elsif (a >= 64 && a < 192 && b < 64) || (a < 64 && b >= 64 && b < 192)
      # middle low
      c = color_random(r)
    else
      # low low
      c = color_high(r)
    end

    # Decide order

    d = r.rand * 3
    colors = [a, b, c]
    colors.shuffle!(random: r)

    colors
  end

  def generate_tag_text_color(colors)
    # See http://www.w3.org/TR/AERT#color-contrast
    o = ((((colors[0] * 299) + (colors[1] * 587) + (colors[2] * 114)) / 1000) + 0.5).to_i
    if o > 125
      [0, 0, 0]
    else
      [255, 255, 255]
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])

    @recipes = Recipe.where(:user_id => params[:id]).reverse
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  def index
    @recipes = Recipe.last(5)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 4.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li class='nav-item'><%= link_to 'Users', users_path, class: 'nav-link' %></li>
  <li class='nav-item'><%= link_to 'My profile', current_user, class: 'nav-link' %></li>
  <li class='nav-item'><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete', class: 'nav-link' %></li>
<% else %>
  <li class='nav-item'><%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %></li>
  <li class='nav-item'><%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %></li>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 4.0 %>
<div class="container">
  <nav class="navbar bg-inverse">
    <div class="navbar-toggleable-xs" id="exCollapsingNavbar2">
      <ul class="nav navbar-nav">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: 'nav-link' %>
        </li>
        <%= render 'layouts/navigation_links' %>
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>
  </nav>
</div>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li class='nav-item'><%= link_to 'About', page_path('about'), class: 'nav-link' %></li>
<li class='nav-item'><%= link_to 'Recipes', recipes_path, class: 'nav-link' %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Kitchen" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Kitchen" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
    <%= render 'layouts/messages' %>
    <%= yield %>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>
  About
<% end %>
<h3>About Kitchen</h3>
<p>
This website was created by <%= link_to 'Josh Hawkins', 'https://hawkins.is' %>
as a means of tracking simple recipes without having to read every food blogger's
life story just to get a shopping list.
</p>
<p>
The entire website is open sourced on
<%= link_to 'GitHub', 'https://github.com/hawkins/Kitchen' %> if you're
interested to contribute or learn morea bout how it works!
</p>

app/views/recipes/_editform.html.erb
<%= form_with model: @recipe, local: true, class: "form" do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :ingredients %><br>
    <%= form.text_area :ingredients %>
  </p>

  <p>
    <%= form.label :content %><br>
    <%= form.text_area :content %>
  </p>

  <p>
    <%= form.label :notes %><br>
    <%= form.text_area :notes %>
  <p>

  <p>
    <%= form.label :tags %><br>
    <%= form.text_field :tags %>
  </p>

  <p>
    <%= form.label :source %><br>
    <%= form.text_area :source %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

<style>
.form input,
.form textarea {
  width: 100%
}
.form textarea {
  min-height: 5rem;
}
</style>

<%= link_to 'Cancel', recipes_path %>

app/views/recipes/_recipe.html.erb
<td>
  <%= link_to recipe.title, recipe %>
</td>

app/views/recipes/edit.html.erb
<h1>Edit Recipe</h1>

<%= render "editform.html.erb" %>

app/views/recipes/index.html.erb
<h3>Recipes</h3>
<%= link_to 'Post New Recipe', 'recipes/new' %>
<table class="table column">
  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <%= render recipe %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render "editform.html.erb" %>

app/views/recipes/search.html.erb
<h3>Search for Recipes</h3>
<form>
  <label>Search</label>
  <input type="text" name="term" value="<%= params[:term] %>" />
  <input type="submit" value="Search"/>
</form>
<table class="table column">
  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <%= render recipe %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/recipes/show.html.erb
<h3>
  <%= link_to @recipe.title, @recipe %>
</h3>

<p>
<i>Created on</i>
<%= @recipe.created_at.strftime("%b %e %Y at %I:%M %p") %><% if @recipe.updated_at - @recipe.created_at > 600 %>,
  <i>last updated on</i>
  <%= @recipe.updated_at.strftime("%b %e %Y at %I:%M %p") %>
<% end %>
</p>

<p>
  Created by <%= link_to User.find(@recipe.user_id).name, User.find(@recipe.user_id) %>
  <% if current_user and current_user.id == @recipe.user_id %>
    (<%= link_to 'edit', edit_recipe_path(@recipe) %>)
  <% end %>
</p>

<% if !@recipe.tags.nil? and !@recipe.tags.empty? %>
  <div style="margin-bottom: 1rem;">
    <strong>Tags:</strong>
    <% @recipe.tags.split(",").each do |tag| %>
      <a
        class="tag"
        style="<%= generate_tag_css(tag.strip) %>"
        href="/recipes/search?tag=<%= URI.encode(tag.strip) %>">
        <%= tag.strip %>
      </a>
    <% end %>
  </div>
<% end %>

<div>
<strong>Ingredients:</strong>
<ul>
  <% @recipe.ingredients.split("\n").each do |ing| %>
    <li>
      <strong><%= ing.split(", ", 2)[0].strip %></strong>
      <% if ing.include? ", " %>
        <span>
          (<%= ing.split(", ", 2)[1].strip %>)
        </span>
      <% end %>
    </li>
  <% end %>
</ul>
</div>

<div>
<strong>Instructions:</strong>
<ol>
  <% @recipe.content.split("\n").each do |line| %>
    <li><%= line %></li>
  <% end %>
</ol>
</div>

<% unless @recipe.notes.nil? || @recipe.notes.empty? %>
  <div class="notes">
    <strong>Notes:</strong>
      <% @recipe.notes.split("\n").each do |line| %>
        <p><%= line %></p>
      <% end %>
  </div>
<% end %>

<style>
.tag {
  /* Background */
  padding: .2em .6em .3em;
  border-radius: .25em;
  /* Spacing */
  line-height: 1.8;
  margin: 0 .1em;
}
.notes p {
  padding-left: 40px;
}
</style>

<% unless @recipe.source.nil? or @recipe.source.empty? %>
  <%= link_to('View source', @recipe.source) if @recipe.source %>
<% end %>

app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>

app/views/users/index.html.erb
<h3>Users</h3>
<table class="table column">
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <%= render user %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/show.html.erb
<h3><%= @user.name %></h3>

<% if current_user and current_user.id == @user.id %>
  <%= link_to 'Edit account', edit_user_registration_path %>

  <p>Email: <%= @user.email if @user.email %></p>

  <%= link_to 'Post New Recipe', 'recipes/new' %>
<% end %>

<h4>Recipes</h4>
<ul>
  <% @recipes.each do |recipe| %>
    <li>
      <%= link_to recipe.title, recipe %> from <%= recipe.created_at.strftime("%b %e %Y at %I:%M %p") %>
    </li>
  <% end %>
</ul>

app/views/visitors/index.html.erb
<h3>Welcome to Kitchen</h3>
<form action="/recipes/search">
  <label>Search for Recipes</label>
  <input type="text" name="term"/>
  <input type="submit" value="Search"/>
</form>
<%= link_to 'Post new Recipe', new_recipe_path %>
<table class="table column">
  <thead>
    <tr>
      <th>
        Newest Recipes
      </th>
    </tr>
  </thead>
  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <%= render recipe %>
      </tr>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <td>
        ... <%= link_to 'View all ' + Recipe.count.to_s + ' recipes', recipes_path %>
    </td>
    </tr>
  </tfoot>
</table>